name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Run the Gradle build task, excluding JUnit tests
      - name: Run the Gradle Build (Exclude Tests)
        run: ./gradlew build -x test

      # Archive Jar with Dependencies
      - name: Archive Jar with Dependencies
        uses: actions/upload-artifact@v2
        with:
          name: Jar with Dependencies
          path: build/libs
